### ISSUE TITLE
执行npm install -g @tars/tars2node命令一直报错

### ISSUE THREAD

**Issue by wyake** [Tencent/Tars#101]
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@tars/
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @tars/tars2node
npm ERR! 404 
npm ERR! 404  '@tars/tars2node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the na
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request
npm ERR!     /home/yake/npm-debug.log

**Comment by loveyacper** [comment]
文档已经更新；这里tars2node是cpp代码编译生成的可执行文件，鉴于跨平台问题暂时没有放到npm中
