### ISSUE TITLE
服务重启的时候经常会出现coredump

### ISSUE THREAD

**Issue by walkbrain** [Tencent/Tars#105]
Core was generated by `/usr/local/app/tars/tarsnode/data/tars.tarsnotify/bin/tarsnotify --config=/usr/'.
Program terminated with signal 6, Aborted.
#0  0x00007f3e226eb1d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.4.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f3e226eb1d7 in raise () from /lib64/libc.so.6
#1  0x00007f3e226ec8c8 in abort () from /lib64/libc.so.6
#2  0x00007f3e22fef9d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f3e22fed946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f3e22fed973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f3e22fedb93 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x000000000054f07d in tars::TC_ThreadMutex::lock (this=this@entry=0xb97b40 <tars::ServantProxyThreadData::_mutex>)
    at /root/Tars/cpp/util/src/tc_thread_mutex.cpp:69
#7  0x00000000004cbe13 in TC_LockT (mutex=..., this=<synthetic pointer>) at /root/Tars/cpp/util/include/util/tc_lock.h:63
#8  tars::ServantProxyThreadData::~ServantProxyThreadData (this=0x7f3e14000c10, __in_chrg=<optimized out>)
    at /root/Tars/cpp/servant/libservant/ServantProxy.cpp:120
#9  0x00000000004cbfa9 in tars::ServantProxyThreadData::~ServantProxyThreadData (this=0x7f3e14000c10, __in_chrg=<optimized out>)
    at /root/Tars/cpp/servant/libservant/ServantProxy.cpp:140
#10 0x00007f3e238c1bc2 in __nptl_deallocate_tsd () from /lib64/libpthread.so.0
#11 0x00007f3e238c1dd3 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f3e227ad76d in clone () from /lib64/libc.so.6

**Comment by loveyacper** [comment]
目前已经解决，请更新代码。

**Comment by varoupt** [comment]
请问是如何解决的？
