### ISSUE TITLE
关于阅读ServantProxy中的一个疑问?

### ISSUE THREAD

**Issue by eric2016fly** [Tencent/Tars#114]
请问, 为什么ServantProxy的invoke函数中调用CommunicatorEpoll的notify只是通过创建了一个socket然后将该socket的可读事件让CommunicatorEpoll线程监控,为什么调用完这一步, CommunicatorEpoll线程就会在epoll_wait中得到刚才创建的那个socket的可读事件?还是说我遗漏了哪一步?

**Comment by helloopenworld** [comment]
交互过程是这样的，实际上调用线程与网络线程交互利用了fd在epoll里事件的改变来通知网络线程，现在比较好的做法利用eventfd来做事件通知。

**Comment by eric2016fly** [comment]
我已经理解了源码，并不是新建的socket是可读的，而是创建了socket后,如果直接将其加入到epoll监听中，epoll_wait会返回这个socket的EPOLLHUP事件，我已经写代码做个验证了，作者应该是通过这个机制来notify，epoll线程的

**Comment by helloopenworld** [comment]
是的
