### ISSUE TITLE
Reactor构造函数中,每次都会实例化一个Acceptor,多个Reactor可以共用一个Acceptor实例吧?

### ISSUE THREAD

**Issue by 0704681032** [Tencent/Tars#12]
👍 
仔细的阅读了net包下面的源代码,相比netty,显然这个更适合先学习,事实上也的确帮我理清了很多思路。
再次 👍 

Reactor.java构造函数中,每次都会实例化一个Acceptor,多个Reactor可以共用一个Acceptor实例吧?

**Comment by knfcn** [comment]
理论上是可以共用一个
