### ISSUE TITLE
期待能支持C#，一样可以跑Linux

### ISSUE THREAD

**Issue by geffzhang** [Tencent/Tars#120]
微软已经开源.NET 版本叫.NET Core ,支持跨平台，支持Linux， 这个微服务框架非常强悍，已经支持了Java，C++，NodeJs， 期待能有支持C# 。新一代的.NETCore专门为微服务而设计，微软也在Github上开源的，地址https://github.com/dotnet 。 而且Mono 也很成熟了，最新的解释器就很好 http://www.mono-project.com/news/2017/11/13/mono-interpreter/

**Comment by leegkon** [comment]
同问

**Comment by yangyulin007** [comment]
why not support .NET Core

**Comment by WayneShao** [comment]
I'm looking forward to it.

**Comment by xhanglizhu** [comment]
期待能有支持C#

**Comment by wangchengqun** [comment]
.net core 性能非常好而且跨平台。希望给予支持谢谢！

**Comment by bywjustin** [comment]
关注，目前正需要
如果有不知道是否有计划支持.net core

**Comment by ShiWei-L** [comment]
.net core 天生跨平台，高性能，采用中间件模式。希望支持

**Comment by kw13202** [comment]
期待能有支持C#

**Comment by liuyl1992** [comment]
Looking forward to support. Net core cross-platform

**Comment by geffzhang** [comment]
#121 相同问题，已经拉微信群沟通
