### ISSUE TITLE
为什么服务发布的时候一直报：找不到或无法加载主类 com.qq.tars.server.startup.Main

### ISSUE THREAD

**Issue by a37803464** [Tencent/Tars#123]
服务发布的时候一直报：找不到或无法加载主类 com.qq.tars.server.startup.Main，这个项目是源码包java的example文件下的quickstart-server项目

**Comment by knfcn** [comment]
问题是否解决？

**Comment by a37803464** [comment]
还没

**Comment by a37803464** [comment]
该问题已解决，替换resin服务器/webapps/tars/WEB-INF/classes下面的frame.zip为最新版，重启服务即可。在此感谢 tars支持-kahn 的耐心帮助！
