### ISSUE TITLE
Tars协议中Tag长度限制问题

### ISSUE THREAD

**Issue by u203** [Tencent/Tars#127]
每一个数据由两个部分组成，如下图：
| 头信息 | 实际数据 |
而其中头信息包括以下几个部分：
| Type(4 bits) | Tag 1(4 bits) | Tag 2(1 byte) |
Tag 2是可选的，当Tag的值不超过14时，只需要用Tag 1就可以表示；当Tag的值超过14而小于256时，Tag 1固定为15，而用Tag 2表示Tag的值。Tag不允许大于255。

如果我要传输的map.size() > 255，是否就无法完成Tars协议的的序列化？

**Comment by loveyacper** [comment]
tag是一个字节表示的，有大小限制。可以考虑通过struct嵌套避免大tag，这样的数据结构组织也更有意义。
