### ISSUE TITLE
框架基础服务打包出错求助

### ISSUE THREAD

**Issue by ladyhua** [Tencent/Tars#13]
我按照安装文档Install.md进行安装配置到4.1节时，在/cpp/build/目录下执行make framework-tar报错，报错信息是make: *** No rule to make target `framework-tar'.  Stop.求指教是什么问题？小白求教

**Comment by zergl** [comment]
切换到cpp/目录下执行make framework-tar，不是在cpp/build下执行。

这个mk管理确实有些误导新手，第一直觉是应该在build/目录下执行的。

**Comment by helloopenworld** [comment]
进入/cpp/build/执行./build.sh all后，再执行make framework-tar

**Comment by ladyhua** [comment]
谢谢，已经解决
