### ISSUE TITLE
Tars框架高可用疑问

### ISSUE THREAD

**Issue by u203** [Tencent/Tars#133]
tarsAdminRegistry, tarsregistry, tarsnode, tarsconfig, tarspatch,tarsstat, tarsproperty,tarsnotify, tarslog，tarsquerystat，tarsqueryproperty
哪些服务原本是设计就是单点的？
哪些服务支持水平扩展？
希望在docs中能提供更加完善的描述

**Comment by helloopenworld** [comment]
这些服务都是支持水平扩展的。。关于扩展我们在后续文档中完善

**Comment by xcwen** [comment]
文档呢:>
