### ISSUE TITLE
php/tarsclient/tars2php文件的几个问题

### ISSUE THREAD

**Issue by ezrealan** [Tencent/Tars#136]
1，tars协议文件中自定义字段中有包含“module”单词时，解析不正确，建议加一个“;”作为判断条件。
2，有几个_tarsAssistant写成了_tafAssistant
3，trim($line)[0] === '/' 中trim($line)[0]可能会有数组越界的问题 建议先判断trim($line)是否为空

**Comment by meijing0114** [comment]
1. 针对包含module、enum、struct等关键字的情况，已经进行了忽略处理，不会报错，也不影响文件的生成；
2. 已经修复
3. 已经修复

在最近的三次php相关的commit中可以体现。
