### ISSUE TITLE
源码包java的example文件下的quickstart-server项目,启动报错,求支持

### ISSUE THREAD

**Issue by anymijun** [Tencent/Tars#140]
服务发布的时候查看日志报：找不到或无法加载主类 com.qq.tars.server.startup.Main，用的demo是项目是源码包java的example文件下的quickstart-server项目.
1.替换resin服务器/webapps/tars/WEB-INF/classes下面的frame.zip为最新版，重启服务,不行.
2.jdk都为1.8且为oracle.
请问下还有什么原因会导致?

---我查了下/usr/local/app/tars/tarsnode/data/TestApp.HelloServer/bin/tars_start.sh 启动脚本中最后一句为,com.qq.tars.server.startup.Main,可是我发布的是war包,怎么会有这个启动项呢?

**Comment by LawlietLi** [comment]
如果使用1.0.3新版，请更新一下java模版文件

**Comment by anymijun** [comment]
更新模版后,能正常启动,感谢@LawlietLi
