### ISSUE TITLE
发布服务如何调用自己的.conf文件

### ISSUE THREAD

**Issue by CoderShengsheng** [Tencent/Tars#143]
make tar 的时候会将目录下的conf文件打到tar中，服务上传后在bin目录下能发现执行程序和conf文件。
但是该目录下生成的sh文件指定的conf文件并不是该目录下的conf文件。是要把调用指定conf文件直接写到代码里吗

**Comment by loveyacper** [comment]
是的；因为是业务自定义配置，内容要自己读取的。
启动命令指定的配置是tars框架使用的。

**Comment by CoderShengsheng** [comment]
在代码里将启动配置文件改为自定义配置文件，没有用系统生成的配置文件
