### ISSUE TITLE
tars-client version in pom.xml should be 1.0.2 or 1.0.3

### ISSUE THREAD

**Issue by mars00772** [Tencent/Tars#145]
when runing ` mvn clean package` to get tars.war but got this:
```
Could not resolve dependencies for project com.qq:tars:war:1.0.0-SNAPSHOT
```
a rough google search gave an answer:
tars-client version in pom.xml should be 1.0.2 or 1.0.3
https://github.com/Tencent/Tars/blob/6bc0c4b24fa968dc2b1ce31f5a5fc9ee9f65da97/web/pom.xml#L83

**Comment by LawlietLi** [comment]
已经更新版本
