### ISSUE TITLE
可以通过tars自带读取配置的方式读取自己配置内容吗。

### ISSUE THREAD

**Issue by CoderShengsheng** [Tencent/Tars#150]
如题，
或者下面的这种代码可以读出来吗。
TC_Config conf("Config.conf");
如上编译报错：no matching function for call to 'tars::TC_Config::TC_Config(const char [18])'
     TC_Config conf("AccessServer.conf");

或者说push后的配置文件如何读取。有没有类似的demo代码

**Comment by loveyacper** [comment]
你可以看一下头文件或者tars中已有代码的config解析方法。
正确用法：
TC_Config conf；
conf.parseFile("Config.conf");

**Comment by CoderShengsheng** [comment]
谢谢，已经按照这种方式解决。
代码可以优化为conf.parseFile(ServerConfig::BasePath+"Config.conf")，这样可以调用push的配置文件。
