### ISSUE TITLE
[Java]怎么做单元测试？

### ISSUE THREAD

**Issue by hank-whu** [Tencent/Tars#155]
支持客户端直连服务端吗？
类似于https://dubbo.gitbooks.io/dubbo-user-book/content/demos/explicit-target.html
没找到相应的Tars文档.

**Comment by loveyacper** [comment]
支持直连。endpoint格式类似  app.server.objname@tcp -h 10.18.1.123 -p 6379

**Comment by hank-whu** [comment]
是可以的，多谢
