### ISSUE TITLE
What's the differences between Tars and MSEC?

### ISSUE THREAD

**Issue by leopeng1995** [Tencent/Tars#16]
Tencent MSEC:
> It is a backend DEV &OPS engine, including RPC,name finding,load balance,monitoring,release and capacity management.

Tencent Tars:
> Tars is a highly performance rpc framework based on naming service using tars protocol and provides a semi-automatic operation platform.

As I understand, the functionalities of Tars seem to be a subset of MSEC. Have I understood correctly?

**Comment by zergl** [comment]
1. They are to two separate projects. Both of them are open-sourced by [Tencent](https://www.tencent.com), but from different business group. MSEC is from Social Network Group (SNG, 社交网络事业群), Tars is from Mobile Internet Group(MIG, 移动互联网事业群)。

2. Both of them are Dev&Ops solution, with the abilities of RPC service, name finding, load balance,monitoring and stat,release control,etc.. BUT, in terms of overall architecture, source code organization, code implement and deploy management, Tars looks "more succint".

3. Tars is not a subset of MSEC.
1. They are to two separate projects. Both of them are open-sourced by [Tencent](https://www.tencent.com), but from different business group. MSEC is from Social Network Group (SNG, 社交网络事业群), Tars is from Mobile Internet Group (MIG, 移动互联网事业群)。

2. Both of them are Dev&Ops solution, with the abilities of RPC service, name finding, load balance,monitoring and stat,release control,etc.. BUT, in terms of overall architecture, source code organization, code implement and deploy management, Tars looks "more succint".

3. Tars is not a subset of MSEC.
