### ISSUE TITLE
[Java]如何平滑关闭客户端？

### ISSUE THREAD

**Issue by hank-whu** [Tencent/Tars#162]
文档和Demo都没有平滑关闭客户端的例子
Communicator应该添加上关闭的方法

**Comment by hank-whu** [comment]
TicketManager 和 Communicator 中都使用了线程池，但是没有正确关闭掉他们

**Comment by LawlietLi** [comment]
该问题已修复，调用Communicator和LogFactory提供了关闭方法，调用后平滑关闭

**Comment by hank-whu** [comment]
可以了，最好能发个mvn版本
