### ISSUE TITLE
性能和dubbo相比如何？

### ISSUE THREAD

**Issue by jipengfei-jpf** [Tencent/Tars#19]
性能和dubbo相比如何？

**Comment by LNGi** [comment]
我觉得吧，这种大型框架，敢在腾讯内部大规模用，说明性能是非常高的，根本没必要去担心这个性能问题。

至于和 dubbo 比，打个比方，就像两个顶级运动员相比，就算他们之间差别达到 20%，那也是顶级选手之间的 20%，再次也不是我等普通人能匹及的。所以需要用就去用就是了，没必要计较什么性能和某某某差多少。

**Comment by patrickhe** [comment]
性能测试文档：
https://github.com/Tencent/Tars/blob/master/docs/tars_performce.md
把CPU占满、网卡占满的情况都测到了。

不过没有同台竞技的测试，谁有兴趣可以尝试一下。

**Comment by guotie** [comment]
为什么java的性能比c++性能还高？
