### ISSUE TITLE
Java源码中com.qq.tars.rest.RestServantAdapter是否没有开源？

### ISSUE THREAD

**Issue by chenghanpeng** [Tencent/Tars#191]
SpringAppContext引用了com.qq.tars.rest.RestServantAdapter。但是没有看到对应的代码？请问是否没有开源？

**Comment by LawlietLi** [comment]
是的

**Comment by chenghanpeng** [comment]
能否上传？或者修改Spring这个项目的SpringAppContext文件。否则这属于半拉子工程。

**Comment by LawlietLi** [comment]
嗯，先把 这个部分移除吧，多谢建议

2018-04-20 9:43 GMT+08:00 chenghanpeng <notifications@github.com>:
