### ISSUE TITLE
CPP实现中通信模型的几个问题

### ISSUE THREAD

**Issue by chenghanpeng** [Tencent/Tars#195]
1。epoll_server中包含的最多neThread设置为15？原因是什么？未什么不把最大值设置成类似处理器的个数，例如[numprocess ~2* numprocessor]
2. 在epoller的创建时候，设置了最大连接参数10240。该参数在创建时被内核忽略，但是在epoll_wait时候控制最大监控的数量。问题是10240的来源？是否一次读取太大？有无测试支持？
3。netThread[0]用于处理bind，即作为Reactor。随后的代码在连接进入时，选择getNetThreadOfFd（）并不区别Reactor和worker，即新的连接也可以进入netThread[0]，这样在处理业务的时候是否影响新进入的连接？为什么不选择让netThread[0]只处理新的连接？

**Comment by loveyacper** [comment]
1.netthread瓶颈在网卡而不是CPU；15个已经足够大，具体参数交给配置文件让业务根据流量自己调整
2.epoll-wait必须指定本次wait的最大事件数量啊，如果指定太多，可能会导致和消费者线程（逻辑处理）的不平衡
3.一个比较难抉择的问题；如果用单独的bind线程（本人也倾向这一点），work线程中连接数据事件的处理阻塞并不会影响新连接接入；
不过tars的定位并不是像nginx那样做接入，也是默认长连接，因此也不会有太频繁的连接创建；目前tars这种做法也没有问题。当然要拿tars作为接入服务，可能需要独立的bind线程（but why not nginx？）

**Comment by chenghanpeng** [comment]
多谢回复。是不是可以这样理解：
1。你们在应用的过程中，发现线程数目和核数无关，流量其主要作用，所以不用关注。那是不是对于高频的小流量场景来说，可能存在流量不足，挑度不够的情况？ 另外对于你说的，tars区分网络线程和逻辑线程是什么意思？你是指CommunicatorEpoll中使用了AyncProcThread来处理业务吗？如果是这样的话，实际上Netty也推荐这样使用（boss负责连接，workers服务网络请求，业务最好使用自己的线程池，不要占用worker，否则也会出问题）
2。我对代码epoll-wait的感觉是不是一次取太多了10240个。为什么不设置小一些，不如1024。然后循环多次呢？
3。对了，还有一小额外的问题，那就是你们设计这块网络的时候，为什么没有考虑使用一些开源的框架，比如CPP的libevent，Java的Netty。而是全部自己实现呢？能共享一些你们的思路吗？再次感谢！

**Comment by loveyacper** [comment]
1.tars区分网络线程和逻辑线程：以接收请求为例，网络线程负责收包，放到请求队列；逻辑线程(handle)从请求队列取包做处理。netty没有内置这种场景，boss负责连接，work负责请求，但是收包和处理都是在worker线程内完成，没有跨线程所以也没有请求队列。C++的muduo也是这样。
2.  epoll_wait(_iEpollfd, _pevs, _max_connections + 1, millsecond);
这块有点误导，但实际运行正常，是这样的： 尽管第三个参数是10240,你注册的event一般是没有这么多的(假设是nEvents)，所以它这里最多返回事件数量是max(10240, nEvents);这块不用太纠结
3.据从java同学了解，有使用netty的打算。cpp呢，实在是没有这样的“标准库”，再加上开发较早（2009年），以及撸一个可用的基础网络代码并没有什么门槛，前辈们就这样自己写了吧。

**Comment by chenghanpeng** [comment]
非常感谢。
大概了解选择这些魔数的缘由和适用的场景，再次感谢！
从一个开源的框架来说，如果把这些魔数和场景配置化，可能更好，能适应更多不同的情况。
