### ISSUE TITLE
php ext api decode error TARS_DECODE_ERROR

### ISSUE THREAD

**Issue by reiyi2007** [Tencent/Tars#198]
用tup-php里的纯PHP解码没问题
用tars2php里的ext扩展解码就报错了
用的是php7.2.4, php扩展开发不太熟, 源码还在看, 求大神有空帮忙看看, 谢谢

tars define:
struct ClientInfoList
{
    0 require map<int, ClientInfo> ClientInfo;
};

struct ClientInfo
{
    0 require string client_name;             
    1 require unsigned int client_id;         
    2 require string client_loginip;          
    3 require unsigned int client_loginport;  
    4 require ClientRole client_role;   
    5 require long client_logintime;          
    6 require GateWayType gateway_type;       
    7 require unsigned int region_id;         
    8 optional string dev_model;              
    9 optional bool is_online;                
    10 optional string client_sdk_ver;        
    11 optional string client_hardware_ver;   
    12 optional string client_firm_ver;       
};

enum ClientRole
{
    CLIENT_ROLE_USER = 0,     
    CLIENT_ROLE_DEVICE = 1,   
};

enum GateWayType
{
    TYPE_DEVICE_GATEWAY = 1,  
    TYPE_USER_GATEWAY = 2,    
};
`<?php
$decodeData=hex2bin("08000206001d0000010c0606726573756c741d0000710a0800010c1a060d313030303030303030303030311300000000cc400002260e3137322e31382e3139332e323032320000b79e400153000001630626f30760017001a60b312e302e332e3044424732b60e544553545f48415244565f312e30c60e544553545f4649524d565f312e300b0b");
$obj = new \app\server\servant\ClientInfoList;
\TUPAPI::getStruct('result', $obj, $decodeData);

// exception code:TARS_DECODE_ERROR(-3)
// 08 00 02 #map size=2
//     06 00 #key1=""
//     1d 00 00 01 0c #val1=simplelist,value=0
//     06 06 72 65 73 75 6c 74 1d 00 00 71 #key2="result"
//     1d 00 00 71 #val2=simplelist,value=struct
//         0a #struct begin
//             08 00 01 #map size=1
//                 0c #key=0
//                 1a #value=struct begin
//                     06 0d 31 30 30 30 30 30 30 30 30 30 30 30 31 #0=1000000000001
//                     13 00 00 00 00 cc 40 00 02 #1=3426746370
//                     26 0e 31 37 32 2e 31 38 2e 31 39 33 2e 32 30 32 #2=172.18.193.202
//                     32 00 00 b7 9e #3=47006
//                     40 01 #4=1
//                     53 00 00 01 63 06 26 f3 07 #5=1524816605959
//                     60 01 #6=1
//                     70 01 #7=1
//                     a6 0b 31 2e 30 2e 33 2e 30 44 42 47 32 #11=1.0.3.0DBG2
//                     b6 0e 54 45 53 54 5f 48 41 52 44 56 5f 31 2e 30 #12=TEST_HARDV_1.0
//                     c6 0e 54 45 53 54 5f 46 49 52 4d 56 5f 31 2e 30 #13=TEST_FIRMV_1.0
//                 0b #struct end
//         0b #struct end
`

**Comment by reiyi2007** [comment]
demo
`<?php
$obj = new app\server\servant\classes\ClientInfoList();
$decodeData = hex2bin('08000206001d0000010c0606726573756c741d0000710a0800010c1a060d313030303030303030303030311300000000cc400002260e3137322e31382e3139332e323032320000b79e400153000001630626f30760017001a60b312e302e332e3044424732b60e544553545f48415244565f312e30c60e544553545f4649524d565f312e300b0b');
\TUPAPI::getStruct('result', $obj, $decodeData);

// exception code:TARS_DECODE_ERROR(-3)
// 08 00 02 #map size=2
//     06 00 #key1=""
//     1d 00 00 01 0c #val1=simplelist,value=0
//     06 06 72 65 73 75 6c 74 1d 00 00 71 #key2="result"
//     1d 00 00 71 #val2=simplelist,value=struct
//         0a #struct begin
//             08 00 01 #map size=1
//                 0c #key=0
//                 1a #value=struct begin
//                     06 0d 31 30 30 30 30 30 30 30 30 30 30 30 31 #0=1000000000001
//                     13 00 00 00 00 cc 40 00 02 #1=3426746370
//                     26 0e 31 37 32 2e 31 38 2e 31 39 33 2e 32 30 32 #2=172.18.193.202
//                     32 00 00 b7 9e #3=47006
//                     40 01 #4=1
//                     53 00 00 01 63 06 26 f3 07 #5=1524816605959
//                     60 01 #6=1
//                     70 01 #7=1
//                     a6 0b 31 2e 30 2e 33 2e 30 44 42 47 32 #11=1.0.3.0DBG2
//                     b6 0e 54 45 53 54 5f 48 41 52 44 56 5f 31 2e 30 #12=TEST_HARDV_1.0
//                     c6 0e 54 45 53 54 5f 46 49 52 4d 56 5f 31 2e 30 #13=TEST_FIRMV_1.0
//                 0b #struct end
//         0b #struct end
`

**Comment by bobzhangyong** [comment]
tars2php 的工具有点小问题，unsigned int类型被识别成了 int类型

麻烦把生成的 ClientInfo.php文件中 \TARS::INT32 修改为 \TARS::UINT32，解包即可正常。

tars2php工具的bug我们会稍候修改提交。

**Comment by bobzhangyong** [comment]
已经修复这个问题，可以使用 phptars 分支代码
