### ISSUE TITLE
部署申请的端口框问题

### ISSUE THREAD

**Issue by TCZWJ** [Tencent/Tars#201]
使用的是centos系统，浏览器是firefox。已安装好tars，但是每次申请发布的时候，填写端口，端口框非常之小，而且不可调整，填写段口号时都不知道填写的是多少。

**Comment by hunjixin** [comment]
ubuntu chrome 也有这个问题

**Comment by souldancer** [comment]
已解决。由于web平台没有对笔记本分辨率做很好的适配，导致在1366分辨率下看端口输入框非常窄。可重新下载相应的页面替换掉原来的页面
