### ISSUE TITLE
php 扩展 实例化 warning 

### ISSUE THREAD

**Issue by xcwen** [Tencent/Tars#210]
```php
<?php

namespace Server\servant\PHPTest\PHPServer\obj\classes;

class SimpleStruct extends \TARS_Struct {
        const ID = 0;
        const COUNT = 1;
        const PAGE = 2;


        public $id; 
        public $count; 
        public $page; 


        protected static $__fields = array(
                self::ID => array(
                        'name'=>'id',
                        'required'=>true,
                        'type'=>\TARS::INT64,
                        ),
                self::COUNT => array(
                        'name'=>'count',
                        'required'=>true,
                        'type'=>\TARS::INT32,
                        ),
                self::PAGE => array(
                        'name'=>'page',
                        'required'=>true,
                        'type'=>\TARS::SHORT,
                        ),
        );

        public function __construct() {
                parent::__construct('PHPTest_PHPServer_obj_SimpleStruct', self::$__fields);
        }
}
$v=new SimpleStruct();
```
运行:
```
localhost:~/tars-tcp-server/src/servant/PHPTest/PHPServer/obj/classes$ php SimpleStruct.php 
PHP Notice:  Accessing static property Server\servant\PHPTest\PHPServer\obj\classes\SimpleStruct::$__field
s as non static in /home/jim/tars-tcp-server/src/servant/PHPTest/PHPServer/obj/classes/SimpleStruct.php on
 line 35                                                                                                 

```

**Comment by bobzhangyong** [comment]
您的php版本是？

**Comment by xcwen** [comment]
7.2 ,  测试时  Notice 提醒打开.

**Comment by bobzhangyong** [comment]
你试试把 $__fields 修改为 $fields 看看能解决问题不

`<?php

namespace Server\servant\PHPTest\PHPServer\obj\classes;

class SimpleStruct extends \TARS_Struct {
        const ID = 0;
        const COUNT = 1;
        const PAGE = 2;


        public $id; 
        public $count; 
        public $page; 


        protected static $fields = array(
                self::ID => array(
                        'name'=>'id',
                        'required'=>true,
                        'type'=>\TARS::INT64,
                        ),
                self::COUNT => array(
                        'name'=>'count',
                        'required'=>true,
                        'type'=>\TARS::INT32,
                        ),
                self::PAGE => array(
                        'name'=>'page',
                        'required'=>true,
                        'type'=>\TARS::SHORT,
                        ),
        );

        public function __construct() {
                parent::__construct('PHPTest_PHPServer_obj_SimpleStruct', self::$fields);
        }
}
$v=new SimpleStruct();`

这样试试

**Comment by xcwen** [comment]
这样可以, 没有报错.

**Comment by bobzhangyong** [comment]
已经修改了，生成的 fields 改为$_fields
