### ISSUE TITLE
Docker 方式搭建Tars环境，不能正常调用服务

### ISSUE THREAD

**Issue by ZhengChuHai** [Tencent/Tars#213]
测试代码
```php
<?php
  require_once("./vendor/autoload.php");

  // 指定主控ip、port
  $config = new \Tars\client\CommunicatorConfig();
  $config->setLocator('tars.tarsregistry.QueryObj@tcp -h 172.17.0.10 -p 17890');
  $config->setModuleName('PHPTest.PHPServer');
  $config->setCharsetName('UTF-8');

  $servant = new Client\servant\PHPTest\PHPServer\obj\TestTafServiceServant($config);

  $name = 'ted';
  $intVal = $servant->sayHelloWorld($name, $greetings);

  echo '<p>'.$greetings.'</p>';
```
报错信息
```
PHP Fatal error:  Uncaught Exception: Rout fail in /data/web/client/vendor/phptars/tars-client/src/Communicator.php:81
Stack trace:
#0 /data/web/client/PHPTest/PHPServer/obj/TestTafServiceServant.php(84): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /data/web/client/test.php(12): Client\servant\PHPTest\PHPServer\obj\TestTafServiceServant->sayHelloWorld('ted', NULL)
#2 {main}
  thrown in /data/web/client/vendor/phptars/tars-client/src/Communicator.php on line 81
```

还有如果是使用容器搭建的环境不能正常的停止应用跟更新代码，如果停止应用或者更新代码，进程会变成僵尸进程。
如图：
![ixi30 qqij j ui jq6 97m](https://user-images.githubusercontent.com/7759644/40574126-c824eaf6-60ff-11e8-8ae6-5a61db43dc49.png)
![49a n4i dg1zosa 9 b5x](https://user-images.githubusercontent.com/7759644/40574128-ca0b1714-60ff-11e8-93f8-43d1e01eb2b0.png)

容器镜像是使用 https://github.com/tangramor/docker-tars 的 php7mysql8 的分支

**Comment by dpp2009** [comment]
defunct问题和基础服务相关，目前在调试中

**Comment by dpp2009** [comment]
https://github.com/Tencent/Tars/issues/219    更新一下docker吧

**Comment by lanrenwo** [comment]
@ZhengChuHai 你好，请问你的问题，解决了吗？我也是报相同的错误....
`
PHP Fatal error:  Uncaught Exception: Rout fail in /data/web/client/vendor/phptars/tars-client/src/Communicator.php:81
Stack trace:
#0 /data/web/client/PHPTest/PHPServer/obj/TestTafServiceServant.php(84): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /data/web/client/index.php(13): Client\servant\PHPTest\PHPServer\obj\TestTafServiceServant->sayHelloWorld('ted', NULL)
#2 {main}
  thrown in /data/web/client/vendor/phptars/tars-client/src/Communicator.php on line 81
`

**Comment by Titanssword** [comment]
@ZhengChuHai @lanrenwo @dpp2009 Hi, I have met the same problem,
```
PHP Fatal error:  Uncaught Exception: Rout fail in /data/examples/tar-tcp-client/vendor/phptars/tars-client/src/Communicator.php:82
Stack trace:
#0 /data/examples/tar-tcp-client/PHPTest/PHPServer/obj/TestTafServiceServant.php(84): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /data/examples/tar-tcp-client/index.php(13): Client\servant\PHPTest\PHPServer\obj\TestTafServiceServant->sayHelloWorld('ted', NULL)
#2 {main}
  thrown in /data/examples/tar-tcp-client/vendor/phptars/tars-client/src/Communicator.php on line 82
```

The docker I used is tarscloud/tars:php, did you guys find some solutions? or could somebody tell me which module is not working?

**Comment by dpp2009** [comment]
提供下进程截图，服务器内网ip，测试脚本截图   等等详细信息

**Comment by Titanssword** [comment]
@dpp2009 感谢您的回复，以下是相关信息，

client
![qq 20190214173219](https://user-images.githubusercontent.com/9337319/52777671-4ea61d80-307f-11e9-87ec-d54a47e78ef7.png)

进程
![qq 20190214173104](https://user-images.githubusercontent.com/9337319/52777635-3d5d1100-307f-11e9-8b5c-e6138204774d.png)
![qq 20190214173131](https://user-images.githubusercontent.com/9337319/52777639-3fbf6b00-307f-11e9-9196-1ad9b6e6a5af.png)

![qq 20190214173330](https://user-images.githubusercontent.com/9337319/52777735-6f6e7300-307f-11e9-91f0-f437bd3cb745.png)

![qq 20190214173425](https://user-images.githubusercontent.com/9337319/52777741-7301fa00-307f-11e9-9ed3-1d04aaafcebf.png)

/data/app_log/PHPTest中的log信息

![image](https://user-images.githubusercontent.com/9337319/52777962-e572da00-307f-11e9-8a18-3531f3f29326.png)

![image](https://user-images.githubusercontent.com/9337319/52778167-54503300-3080-11e9-9648-2b51d0c847ee.png)

composer.json中tars-client 教程中0.1.1找不到，这里使用0.1.5的版本

![image](https://user-images.githubusercontent.com/9337319/52778062-15ba7880-3080-11e9-8c8b-094f22722752.png)

错误：
![image](https://user-images.githubusercontent.com/9337319/52778276-a09b7300-3080-11e9-80e8-b721375ec5dc.png)

**Comment by Titanssword** [comment]
应该是client的版本的问题，将composer.json中的client版本号更新到dev-master
![image](https://user-images.githubusercontent.com/9337319/52778945-1d7b1c80-3082-11e9-94f2-97c671859738.png)

执行composer update
![image](https://user-images.githubusercontent.com/9337319/52779015-456a8000-3082-11e9-9163-4b5917f61275.png)
不好意思，麻烦各位了

**Comment by muyehub** [comment]
@Titanssword 我遇到了相同的问题, 且更新tars-client的包版本为dev-master后也不好使
