### ISSUE TITLE
发布服务错误

### ISSUE THREAD

**Issue by lizhiguo110223** [Tencent/Tars#214]
发布服务，提示：服务发布失败:tars.tarsregistry.QueryObj|connect failed to 192.168.32.100:17890，查看核心服务部署的192.168.32.100上，17890端口没有被占用，是哪个基核心务启动出错了吗？

**Comment by loveyacper** [comment]
是tarsregistry没有启动。 麻烦检测一下日志，是不是访问db权限出问题导致不能启动
