### ISSUE TITLE
编译phptars后make test70%不通过

### ISSUE THREAD

**Issue by cygsxak** [Tencent/Tars#220]
# ISSUE模板：

## 基础信息：
服务器版本：centos6.9
php版本：5.6.36
swoole版本：1.8.13
使用的核心代码版本号：
tars-server：0.1.1 
tars-client：0.1.1 

## 问题描述：
编译扩展phptars中，进行make test测试，近70%失败率！

**Comment by bobzhangyong** [comment]
抱歉 make test 的结果好像不是很准确，我们还在优化
麻烦 用phpunite 测试
cd testcases
php /ProjectDir/phpunit-5.7.12.phar test --debug
php /ProjectDir/phpunit-5.7.12.phar testTARSClient.php --debug
php /ProjectDir/phpunit-5.7.12.phar testTARSServer.php --debug

执行这几个命令试试，其中 /ProjectDir/phpunit-5.7.12.phar 需要自己下载一下

**Comment by copyrenzhe** [comment]
最新的代码中已经修复
