### ISSUE TITLE
TARS能支持pb协议吗

### ISSUE THREAD

**Issue by elftech** [Tencent/Tars#23]

**Comment by helloopenworld** [comment]
可以通过tars的第三方协议来支持

**Comment by elftech** [comment]
@helloopenworld ，有说明文档么。想研究下tars以移植一个后端服务。但客户端用的pb，所以协议不能改。

**Comment by loveyacper** [comment]
在BindAdapter中设置你的协议解析函数即可，函数签名符合 int (string &, string&)即可，其中int是enum值，表示解析结果：  
    enum     {
        PACKET_LESS = 0, // 包还没有收完整
        PACKET_FULL = 1,  // 收到一个完整包
        PACKET_ERR  = -1, // 错误的协议包
    };
