### ISSUE TITLE
php客户端调java服务端，out参数为数组和字符串类型时结果不对，需修改Tars\client\CommunicatorConfig文件中版本号

### ISSUE THREAD

**Issue by cygsxak** [Tencent/Tars#247]
PHP 7.2.6，swoole 2.0.6

php客户端调java服务端，out参数为数组和字符串类型时结果不对，需修改Tars\client\CommunicatorConfig文件中版本号：
修改前 protected $iVersion = 3; 
修改后protected $iVersion = 1;

Tars文件样本 int helloOutSelToInt(string sIn, out string outStr, out int outInt);

**Comment by meijing0114** [comment]
此问题为java服务端对tup的支持未上线导致的。现在master已经解决。
