### ISSUE TITLE
c++的clientsocket里面的异步connect的漏洞

### ISSUE THREAD

**Issue by tsingakbar** [Tencent/Tars#25]
https://github.com/Tencent/Tars/blob/master/cpp/util/src/tc_clientsocket.cpp#L278

这里还是需要处理EPOLLERR和EPOLLHUP的，不是说epoll_wait返回了大于0个就是成功了。
我们项目里面通过tc_http调用到这里的，推测是因为这里没处理一场，导致到了后面的send就会有可能返回ECONNREFUSED。

公司代码库没看到哪里可以提bug，就这里提了，欢迎反馈rtx richieyu。

**Comment by helloopenworld** [comment]
多谢反馈，我们修复一下。
