### ISSUE TITLE
php的模版中定义的各个字段和tars-client中CommunicatorConfig读取模版的字段不对应

### ISSUE THREAD

**Issue by joan2015** [Tencent/Tars#255]
$this->localip = $config['tars']['application']['server']['localip'];
        $this->locator = $config['tars']['application']['client']['locator'];
        $this->logPath = $config['tars']['application']['server']['logPath'];
        $this->logLevel = $config['tars']['application']['server']['logLevel'];
        $this->dataPath = $config['tars']['application']['server']['dataPath'];
        $this->syncInvokeTimeout = $config['tars']['application']['client']['syncInvokeTimeout'];
        $this->asyncInvokeTimeout = $config['tars']['application']['client']['asyncInvokeTimeout'];
        $this->refreshEndpointInterval = $config['tars']['application']['client']['refreshEndpointInterval'];
代码中是logPath，logLevel，dataPath等
模版中

<server>
	   app=${app} 

	   server=${server}

	   localip=${localip}

	   local=${local}

	   basepath=${basepath}

	   datapath=${datapath}

	   logpath=${logpath}

	   loglevel=DEBUG

	   logsize=15M

	   log=tars.tarslog.LogObj

	   config=tars.tarsconfig.ConfigObj

	   notify=tars.tarsnotify.NotifyObj

	   logLevel=DEBUG

	   php=/usr/bin/php

	   buffer_output_size=12582912

	   open_tcp_nodelay=1

	   open_eof_check=0

	   open_eof_split=0

	   task_worker_num=1

都是小写

另外还有字段不一致，如sync-invoke-timeout等

**Comment by dpp2009** [comment]
已经更新了
