### ISSUE TITLE
When database is 5.6.40, cannot deploy new service in tars web

### ISSUE THREAD

**Issue by superbboy** [Tencent/Tars#256]
Here is the error info. 
lDataTruncation: Data truncation: Incorrect datetime value: '0000:00:00 00:00:00' for column 'patch_time' at row 1 ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: INSERT INTO db_tars.t_server_conf ( application, server_name, node_group, node_name, base_path, exe_path, template_name, bak_flag, setting_state, present_state, process_id, patch_version, patch_time, patch_user, tars_version, posttime, lastuser, server_type, start_script_path, stop_script_path, monitor_script_path, enable_group, enable_set, set_name, set_area, set_group, ip_group_name, profile, config_center_port, async_thread_num, server_important_type, remote_log_reserve_time, remote_log_compress_time, remote_log_type ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0000:00:00 00:00:00' for column 'patch_time' at row 1 ; SQL []; Data truncation: Incorrect datetime value: '0000:00:00 00:00:00' for column 'patch_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0000:00:00 00:00:00' for column 'patch_time' at row 1

Following the document of MySQL, "0000:00:00 00:00:00" is not a valid value of datetime when strict mode is on.

**Comment by loveyacper** [comment]
We'll check it. Thanks for point out this problem.

**Comment by tangramor** [comment]
zero value is not supported in the higher version mysql, you need to add mysql start option: --sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 

or add option --sql_mode='' for mysql 8.0

https://github.com/tangramor/docker-tars#mysql

**Comment by wjx82850707** [comment]
We have fixed this bug. please update to the latest version
