### ISSUE TITLE
web-运维管理-部署服务-部署申请 有bug

### ISSUE THREAD

**Issue by benxincaomu** [Tencent/Tars#26]
部署申请点击提交时，弹窗提示“布署申请提交失败！请联系管理员”，后台插入数据库异常
`
org.springframework.dao.DataIntegrityViolationException: 
### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0000:00:00 00:00:00' for column 'patch_time' at row 1

`

**Comment by helloopenworld** [comment]
看看mysql使用的my.cnf的sql_mode是否进行了设置，可以参考Install.md中mysql的安装方法。
