### ISSUE TITLE
tars2php工具生成interface问题

### ISSUE THREAD

**Issue by meijing0114** [Tencent/Tars#262]
如果接口定义 这里多了空格 生成的代码里 就会有一个方法名为空 接口

**Comment by bobzhangyong** [comment]
请注意 tars 文件中 方法名后面，括号前面 的空格。

临时解决方案，在tars2php.php 中 修改880行， $mix = $tokens[0]; 为 $mix = trim($tokens[0]);

**Comment by bobzhangyong** [comment]
Fixed
