### ISSUE TITLE
TARS-php 中 ENVConf.php 文件中什么作用？

### ISSUE THREAD

**Issue by ouewqa** [Tencent/Tars#277]
### What language are you using?
 php
 
src/conf/ENVConf.php
这个文件是干嘛用的，里面的为什么还需要定义 `public static $locator = 'tars.tarsregistry.QueryObj@tcp -h 172.17.0.2 -p 17890';`

搜索所有源代码，没有找到引用的地方。

**Comment by cygsxak** [comment]
这个是主控的地址，客户端代理在调用tars服务端的时候会通过这个配置寻找相应的服务。——调用的地方参考样本中的如下代码段：
```
$config = new CommunicatorConfig();
$config->setLocator(ENVConf::$locator);
```
