### ISSUE TITLE
java调php的tars服务时，当返回参数结构体字段为require时，报空指针错误

### ISSUE THREAD

**Issue by cygsxak** [Tencent/Tars#301]
java调php的tars服务时，当返回参数结构体字段为require时，报空指针错误；

php版本7.2.6 
swoole版本2.0.0以及4.0.0

当把结构体字段改为optional时，可成功调用！

**Comment by dpp2009** [comment]
报空指针错误 是java报的吧   用java作为client？

**Comment by meijing0114** [comment]
此问题主要原因还是PHP client与java client对tars文件中 struct结构的tag数据处理方式不同导致的，将tag从小到大编排，可以解决这个问题。长期来看会保持打包方式的统一。
