### ISSUE TITLE
项目目前适合用于生产环境不？

### ISSUE THREAD

**Issue by xuhuan** [Tencent/Tars#34]
看目前的活跃貌似很低，贡献者也少，网上能搜到的资料也很有限。
基于目前的状况，项目后期还能持续迭代下去的不？

**Comment by helloopenworld** [comment]
适合生产环境，同时也会迭代下去，目前tars的反馈都在qq群里，欢迎加入：579079160。

**Comment by xuhuan** [comment]
@helloopenworld 好的。
