### ISSUE TITLE
关于RegistryServer的高可用设计实现的疑问？

### ISSUE THREAD

**Issue by fznply** [Tencent/Tars#36]
通过个人阅读tars的设计文档理解，RegistryServer作为服务注册发现的服务，client会通过其查询到业务server的可用ip列表，节点server也会通过心跳将业务server状态同步到RegistryServer。有以下疑问，还请熟悉tars的同学解答下：
1. RegistryServer本身是无状态的吗，还是多个RegistryServer形成集群会通过paxos协议自动确定主从？
2. 浏览代码看到其一些数据是存在DB中的，那么RegistryServer是否依赖DB集群实现读写的高可用（client会读RegistryServer、节点server会写RegistryServer）？
3. 是否每一次client调用都会先去读RegistryServer获取可用ip列表，如果是的话RegistryServer服务的压力应该很大，直接读DB的压力如何缓解？

**Comment by tarstest** [comment]
1.RegistryServer本身是无状态、多点部署的，状态数据是存储在DB（采用主备模式）中的，RegistryServer通过定时全量加载和增量加载的方式缓存DB中的状态信息
2.Tars的高可用是通过DB主备、RegistryServer（多点）、NodeServer（每台机器一个）、节点server的路由缓存来实现的
3.client调用时不是每次都去访问RegistryServer获取可用列表，定时去获取的（60s），因为获取可用列表是直接读缓存信息的，所以很快。

**Comment by fznply** [comment]
多谢答疑
