### ISSUE TITLE
Tars文件为什么c++版本中不支持unsigned long类型？

### ISSUE THREAD

**Issue by KimChen2016** [Tencent/Tars#38]
如题，为什么不支持unsigned long类型？
是因为使用的场景比较少还是加上后有什么影响
个人感觉服务器开发中unsigned long的类型使用的还是挺多的

**Comment by helloopenworld** [comment]
c++支持本身是没问题，主要是因为java都是有符号的，因为当时tars做的时候，考虑c++和java都能用，就没有支持无符号64位类型
