### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Tencent/Tars#4]
I would like to point out that identifiers like “[`__CONFIG_SERVER_H_`](https://github.com/Tencent/Tars/blob/2101e43d79d5b6817c2ba2d5e43293ae1e3e9f6e/cpp/framework/ConfigServer/ConfigServer.h#L17 "Update candidate")” and “[`__PROPERTY_HASHMAP_H_`](https://github.com/Tencent/Tars/blob/2101e43d79d5b6817c2ba2d5e43293ae1e3e9f6e/cpp/framework/PropertyServer/PropertyHashMap.h#L17 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by helloopenworld** [comment]
thank you for point out this problem .we will fixed it as soon as possbile

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
