### ISSUE TITLE
tars各个自带的服务都是做什么的，又是怎么保障他们的可靠性的？

### ISSUE THREAD

**Issue by jokenchang** [Tencent/Tars#48]
tars自带的服务有哪些？除了页面看到的tarsconfig/tarslog/tarsnotify/tarspatch/tarsproperty/tarsqueryproperty/tarsquerystat/tarsstat,还有不在管理页面显示的tarsregistry/tarsnode/tarsAdminRegistry，还有其他的服务吗？他们各个服务的具体功能有文档说明吗？除了页面上显示的可以看到他们的状态信息，没显示的怎么方便看到他们的状态信息？又是怎么保障各个服务的高可靠性的？用户又是怎么知道当前的服务是稳定？比如用户重启了服务器后，只需要看下管理页面上的状态信息就能确保服务是正常的吗？如果类似tarsAdminRegistry或者其他服务down了，是否会其他tars服务，如果不影响，那么我看到的管理页面信息都显示正常，我又怎么知道有服务down了？

**Comment by CoderShengsheng** [comment]
这些服务式怎么添加上去的，发布包在哪呢，可以指导下吗

**Comment by louishlz** [comment]
1、tars自带的服务有哪些？除了页面看到的tarsconfig/tarslog/tarsnotify/tarspatch/tarsproperty/tarsqueryproperty/tarsquerystat/tarsstat,还有不在管理页面显示的tarsregistry/tarsnode/tarsAdminRegistry，还有其他的服务吗？他们各个服务的具体功能有文档说明吗？

答：https://github.com/Tencent/Tars/blob/master/Introduction.md  这里的说明文档就有说明

2、tarsregistry/tarsnode/tarsAdminRegistry 属于核心服务，tars整个系统起来之前必须先起来，因此这些答：服务暂时没有管理平台可以管理，必须通过添加相应的监控（比如crontable）来定时检测。后续这些服务的状态我们也会展示到管理平台上来，其实在腾讯公司内部的自动化系统里是有监控体系的。

3、如果类似tarsAdminRegistry或者其他服务down了，是否会其他tars服务，如果不影响，那么我看到的管理页面信息都显示正常，我又怎么知道有服务down了？
答：tarsAdminRegistry是给管理平台操作其它tars服务用的，比如启停服务，发布服务等。一般tarsAdminRegistry都是多节点部署。除了tarsnode和tarsregistry，其它tars的基础服务挂了，不会影响到业务，只会影响到业务的一些统计信息，比如，如果是tarsstat挂了，那么流量，耗时等统计功能可能会受影响而已。具体情况要具体分析。

首先，要明确一点，tars的所有服务都是强烈建议多点部署的，保障好容错容灾！！！！
