### ISSUE TITLE
添加tarsstat服务上不去

### ISSUE THREAD

**Issue by CoderShengsheng** [Tencent/Tars#50]
感觉应该是很简单的一个点，按照文档操作，上传的tarsstat包实在build文件夹下找到的，点击发布
出现：服务发布失败:tars.tarsregistry.QueryObj|connect failed to 10.99.1.132:17890
怎么回事呢，上传的文件不对吗，应该上传哪个文件，或者还是别的地方出了问题

**Comment by louishlz** [comment]
要确保tars.tarsregistry 这个进程是起来的啊

**Comment by CoderShengsheng** [comment]
@louishlz 运行了tars_install.sh，现在反应是发布失败，是因为发布的文件有问题嘛

**Comment by CoderShengsheng** [comment]
运行tars_install.sh开启服务，发布tgz文件，就成功了。
