### ISSUE TITLE
如何不通过指定端口和IP，实现TestHelloClient

### ISSUE THREAD

**Issue by CoderShengsheng** [Tencent/Tars#53]
HelloPrx prx;
        comm.stringToProxy("TestApp.HelloServer.HelloObj@tcp -h 10.120.129.226 -p 20001" , prx);

这行代码如何改成不用指定端口和ip那种的，据说是可以通过调用tars的一个服务或者调度器，有这个功能的相关文档吗？
或者这个功能是可实现的吗？

**Comment by jokenchang** [comment]
comm.setProperty("locator", "tars.tarsregistry.QueryObj@tcp -h ip -p 17890 -t 10000");
comm.stringToProxy("Office.JokenTestServer.HelloObj", prx);

可以通过设置locator，这个是主控服务，通过这个主控可以找到在主控上注册的所有节点的所有服务
