### ISSUE TITLE
浏览器无法连接问题

### ISSUE THREAD

**Issue by WhatDream** [Tencent/Tars#55]
![image](https://user-images.githubusercontent.com/15125028/29237795-6e230d78-7f58-11e7-82d1-d4852e70e7e6.png)
配置好之后，访问出现如上图片所示的问题，求解

**Comment by wjx82850707** [comment]
看异常信息 ，是DB 异常了，可以先检查下DB 是否能正常访问。

**Comment by WhatDream** [comment]
已解决，确实是db的问题，现在是实时状态那里一直都是加载状态，不知道什么原因！！！！！
