### ISSUE TITLE
同一台机器的Servant名是不是必须唯一

### ISSUE THREAD

**Issue by microIBM** [Tencent/Tars#63]
我想在一台机器上部署两个HelloServer, 只是端口不一样。是不是添加Servant时,Servant名必须不一样？
![image](https://user-images.githubusercontent.com/2402651/29239337-e9f38c5e-7f7e-11e7-9399-e7161199f366.png)

**Comment by marklightning** [comment]
同一台的servant名字要不一样才能发布，同一个servant需要发布到不同的节点上

**Comment by loveyacper** [comment]
你的意思应该是想负载均衡吧？实际taf框架内部都会帮你做的，可以启动两个不同的进程，HelloServer的port配置不同即可。client通过主控访问你的HelloServer，就会均衡的访问你这两个进程。

**Comment by louishlz** [comment]
暂时不支持在同一台物理机上部署同样名称的服务(app.server的组合）,比如Test.HelloServer 不部署在同一个机器上的，必须分开在不同机器部署。
