### ISSUE TITLE
用底层通用代码测试一个https请求，报错！底层是否支持ssl?

### ISSUE THREAD

**Issue by utike** [Tencent/Tars#64]
TC_HttpRequest stHttpReq;
stHttpReq.setGetRequest("https://api.bitfinex.com/v1/pubticker/btcusd");
TC_HttpResponse stHttpRep;
int iRet = stHttpReq.doRequest(stHttpRep, 3000);
 if(iRet != 0)
 {
    cout << iRet << endl;
 }

string r = stHttpRep.encode();
cout << r << endl;
cout << "***********************************" << endl;

TC_File::save2file("tmp.html", stHttpRep.getContent());
cout << "***********************************" << endl;
cout << stHttpRep.getContent().length() << endl;

错误信息：
HTTP/1.1 400 Bad Request
CF-RAY: -
Connection: close
Content-Length: 275
Content-Type: text/html
Date: Sat, 12 Aug 2017 11:09:34 GMT
Server: cloudflare-nginx

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

**Comment by loveyacper** [comment]
目前外部tars仅仅支持tcp和udp两种类型；现在内部已经开发了对第三种类型ssl的支持，测试稳定后将发布，敬请期待。
