### ISSUE TITLE
Java和C++都支持客户端和服务端？

### ISSUE THREAD

**Issue by Jaskey** [Tencent/Tars#9]
整个tars项目里面有C++ server , C++ client 和Java Server, Java Client?

如果是的话，是否应该分拆成两个项目维护？

**Comment by helloopenworld** [comment]
Java和C++都支持客户端和服务端，目前在一起，整体性看书去更好些。

**Comment by Jaskey** [comment]
@helloopenworld 
我意思是c++和java单独维护，毕竟版本特性，bug将来都很可能是不同步的，单元测试，打包等等都不一样。分拆两个仓库也方便使用者使用和学习

**Comment by zergl** [comment]
楼主指的是应用开发框架(servant)，所谓“支持”实际是分别用C++和Java实现了同一个思路的框架。

另补充，
1. C++仅支持Linux平台下的客户端和服务器（mac xcode编译已有g友提交PR，未合入）。
2. 为什么不分成两个目录维护？很大可能是应用框架与基础服务（framework）之间的协议是统一的，估计基于此考虑吧。从软件工程管理角度看，_个人也倾向_分拆成两个独立项目管理。

**Comment by luyongfugx** [comment]
如果基础服务（framework）有java版本的就好了，团队里没有c++同学的话还是心里不太有底：）

**Comment by simpleSOA** [comment]
同意楼主的想法，我也倾向两种语言分成两个项目单独来管理，毕竟不是所有团队都有C++和java，虽然只用其中一种，感觉还是那么没有底
