### ISSUE TITLE
|ERROR|ServerObject.cpp:reportMemProperty:706|stream is empty:

### ISSUE THREAD

**Issue by ramosyang** [Tencent/Tars#92]
为什么扩容时出现这样的错误

**Comment by zy0527** [comment]
查看tarsAdminRegistry的日志  发现错误|ERROR|[TARS][CommunicatorEpoll::handleInputImp] connect error tcp -h 192.168.0.115 -p 19385,tars.tarsnode.NodeObj,_connExcCnt=2,No route to host

**Comment by zy0527** [comment]
找到了，是防火墙的问题，扩容服务的端口没打开
