### ISSUE TITLE
编译tars出错了

### ISSUE THREAD

**Issue by lntoly** [Tencent/Tars#99]
错误提示：
[ 53%] Building CXX object framework/NodeServer/CMakeFiles/tarsnode.dir/SingleFileDownloader.cpp.o
[ 53%] Building CXX object framework/NodeServer/CMakeFiles/tarsnode.dir/NodeRollLogger.cpp.o
[ 53%] Building CXX object framework/NodeServer/CMakeFiles/tarsnode.dir/BatchPatchThread.cpp.o
In file included from /root/software/tools/Tars-master/cpp/framework/NodeServer/BatchPatchThread.cpp:20:0:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandPatch.h: In member function ‘virtual int CommandPatch::execute(std::__cxx11::string&)’:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandPatch.h:407:32: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(cmd.c_str());
                                ^
[ 54%] Building CXX object framework/NodeServer/CMakeFiles/tarsnode.dir/ServerImp.cpp.o
[ 54%] Building CXX object framework/NodeServer/CMakeFiles/tarsnode.dir/NodeImp.cpp.o
In file included from /root/software/tools/Tars-master/cpp/framework/NodeServer/NodeImp.cpp:27:0:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandPatch.h: In member function ‘virtual int CommandPatch::execute(std::__cxx11::string&)’:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandPatch.h:407:32: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(cmd.c_str());
                                ^
In file included from /root/software/tools/Tars-master/cpp/framework/NodeServer/NodeImp.cpp:22:0:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandStart.h: In member function ‘bool CommandStart::startByScript(std::__cxx11::string&)’:
/root/software/tools/Tars-master/cpp/framework/NodeServer/CommandStart.h:175:44: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         system(sGetServerPidScript.c_str());
                                            ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
framework/NodeServer/CMakeFiles/tarsnode.dir/build.make:158: recipe for target 'framework/NodeServer/CMakeFiles/tarsnode.dir/NodeImp.cpp.o' failed
make[2]: *** [framework/NodeServer/CMakeFiles/tarsnode.dir/NodeImp.cpp.o] Error 4
CMakeFiles/Makefile2:1377: recipe for target 'framework/NodeServer/CMakeFiles/tarsnode.dir/all' failed
make[1]: *** [framework/NodeServer/CMakeFiles/tarsnode.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

gcc版本是不是太高了
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by lntoly** [comment]
改成g++-4.8也不行

**Comment by lntoly** [comment]
原因找到了，买的云主机。
c++: internal compiler error: Killed (program cc1plus)
按网上说的，是内存不足引起的。
解决方法：http://blog.csdn.net/bxd1314/article/details/47338391

**Comment by wang70937** [comment]
至少2G内存，否则编译出错。我试过的。
